version: '2'

services:
  postgresql:
    image: 'bitnami/postgresql:latest'
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=drawio_user
      - POSTGRESQL_PASSWORD=password123
      - POSTGRESQL_DATABASE=drawio_database
    volumes:
      - /Users/Shared/Volumes/drawio:/bitnami/postgresql
